AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple AWS Lambda for searching book records within a DynamoDB table.
Resources:
  GetBooksFx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/post-tools-fx-1.0.jar
      Handler: src/main/java/com.autozone.post_tools.PostToolsHandler
      Runtime: java8.al2
      Description: Java function
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
        - arn:aws:iam::430213699949:policy/access-sam-storage-bucket